server:
  port: 8090

bot:
  name: BodyMeasurementsBot
#  token: ${SECRET_TG_TOKEN}
  token: 6308845547:AAG5v6snZFy6MmfVq8Mv79uNbuh9Ohk4Nro

messages:
  start: >
    Привет, %s 👋 %n%n
    Я BodyMeasurementsBot - твой личный помощник по ведению здорового образа жизни и достижению твоих фитнес-целей! 🌟 %n%n
    Чтобы получить больше информации о боте, введите команду /info, и чтобы начать работать с ним, введите /help.

  info: >
    Добро пожаловать в раздел помощи! 🤝%n
    ---------------------------------------------------------------------------%n%n
    🏋️‍♂️ Ведение замеров:%n
    - Можешь записывать свой вес и охваты тела, чтобы отслеживать свой прогресс и видеть, как твоя форма меняется со временем.%n
    - Просто отправь мне команду /weight <вес> для ввода текущего веса и /measurements <грудь> <плечи> <таллия> <живот> <бедра> для замера охватов тела.%n
    %n
    🔔 Уведомления:%n
    - Настроить режим занятий - легко!%n
    - Просто скажи мне время, когда ты обычно начинаешь заниматься, и я буду отправлять тебе уведомления о необходимости выполнить упражнения и для других целей!%n
    - И не забудь установить время для получения мотивационных цитат, они помогут поднять твое настроение и вдохновят на успех!%n
    - Используй команды /set_reminder <время> и /set_motivation_time <время> для настройки уведомлений.%n
    %n
    🎯 Расчет прогресса:%n
    - Установи свой целевой вес, и я буду рассчитывать процент потери веса относительно начального значения.%n 
    - Просто скажи мне свой целевой вес командой /set_target_weight <целевой_вес>. А для получения отчета о своем прогрессе, отправь команду /progress.%n
    %n
    ❓ Обратная связь:%n
    - У тебя есть вопросы или предложения? Просто отправь мне команду /feedback <сообщение> и я обязательно отвечу.%n
    %n
    Твое здоровье - это важно, и я здесь, чтобы помочь тебе на каждом шагу к здоровой и активной жизни! 💪

  help: >
    Добро пожаловать в раздел помощи! 🤝%n
    ---------------------------------------------------------------------------%n%n
    Вот список доступных команд и их описание:%n
    %n
    🏋️‍♂️ Ведение замеров:%n
    - /weight <вес>: Записать текущий вес.%n
    - /measurements <грудь> <плечи> <таллия> <живот> <бедра>: Записать охваты тела.%n
    %n
    🔔 Уведомления:%n
    - /set_reminder <время>: Настроить время уведомлений о начале занятий.%n
    - /set_motivation_time <время>: Настроить время ежедневных мотивационных цитат.%n
    - /motivation: Получить случайную мотивационную цитату прямо сейчас.%n
    %n
    🎯 Расчет прогресса:%n
    - /set_target_weight <целевой_вес>: Установить свой целевой вес для расчета прогресса.%n
    - /progress: Получить отчет о прогрессе похудения.%n
    %n
    ❓ Обратная связь:%n
    - /feedback <сообщение>: Отправить сообщение с вопросами или предложениями.%n
    %n
    Для того чтобы воспользоваться какой-либо командой, просто напиши ее в чат.%n
    Например, чтобы записать свой вес, отправь мне команду /weight 70.%n
    %n
    Если у тебя возникли вопросы или нужна помощь, не стесняйся обращаться!%n%n
    Я здесь, чтобы помочь тебе достигнуть здоровых результатов! 💪
